# Generated by Django 4.1.3 on 2025-02-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="play",
            old_name="actor",
            new_name="actors",
        ),
        migrations.AlterField(
            model_name="play",
            name="genre",
            field=models.ManyToManyField(related_name="plays", to="theatre.genre"),
        ),
    ]
