# Generated by Django 5.1.6 on 2025-03-02 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ticket",
            options={"ordering": ["row", "seat"]},
        ),
    ]
