# Generated by Django 5.1.6 on 2025-03-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0005_alter_ticket_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="play",
            name="image",
            field=models.ImageField(null=True, upload_to="?"),
        ),
    ]
