# Generated by Django 4.1.3 on 2025-03-12 14:11

from django.db import migrations, models
import theatre.models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0006_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="image",
            field=models.ImageField(
                null=True, upload_to=theatre.models.play_image_path
            ),
        ),
    ]
