# Generated by Django 4.1.3 on 2025-03-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0007_alter_play_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
